---
title: "Assignment1"
author: "Divine Ingabire"
date: "2026-05-06"
output:
  word_document: default
  html_document: default
---
```{r}
install.packages("haven")
```
```{r}
library(haven)
```
#creating statistical packages data.
```{r}
studentsdata <- data.frame(studentsname=character(0),StudentsID=numeric(0),Marks=numeric(0),Gender=character(0))
```
```{r}
studentsdata <- edit(studentsdata)
```
```{r}
View(studentsdata)
```


```{r}
write_sav(studentsdata, "studentsdata.sav")
```
```{r}
getwd()
```
```{r}
data_from_sp <- read_sav("/Users/macbook/Desktop/AUCA/studentsdata.sav")
```
```{r}
print(data_from_sp)
```

```{r}
View(data_from_sp)
```
```{r}
#install.packages("RMySQL")
```


```{r}
install.packages("RSQLite")
```
```{r}
library(RSQLite)
```

```{r}
library(RMySQL)
```
```{r}
library(DBI)
```

# database
```{r}
getwd()
```

```{r}

```

```{r}
con <- dbConnect(RSQLite::SQLite(),"/Users/macbook/Desktop/AUCA/student.db")
```

# insertdata
```{r}
dbWriteTable(con,"studentstable",studentsdata,overwrite =TRUE)
```
```{r}
data_from_db <-dbReadTable(con,"studentstable")
```
```{r}
View(data_from_db)
```
```{r}
print(data_from_db)
```

```{r}
hist(data_from_sp$studentsname, col="blue")

```





