---
title: "EXERCISEABOUTDPLYR"
author: "Divine Ing."
date: "2026-05-12"
output: html_document
---
#Dplyr function.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
product<-data.frame(product_id=c(1:10),
                    product_name=c("Biscuit","Banana","Orange","Juice","Phone","Yoghurt","Watch","Laptop","Bag","Desk"),
                    Price=c(100,50,10,200,45000,120,2400,60000,19000,90000),
                    Category=c("Foodstuff","Foodstuff","Foodstuff","Foodstuff","Items","Foodstuff","Item","Item","Item","Item"),
                    Quantity=c(1,1,1,1,1,1,1,1,1,1))
product

```
```{r}
library(dplyr)
```

```{r}
install.packages("ggplot2")
```
```{r}
library(ggplot2)
```

```{r}
#install.packages("magrittr")
```
```{r}
library(magrittr)
```
```{r}
#install.packages("tidyverse")
```

```{r}
library(tidyverse)
```

## Filter Function
```{r}
filter(product,Category =="Foodstuff")
```

```{r}
filter(product,Price>10000)
```
## Select

```{r}
select(product,Category)
```

## Mutate
```{r}
mutate(product,totalprice = Price*Quantity)
```
```{r}
mutate(product)
```

## To remove a column
```{r}
select(product, -Quantity)
```

